name: hola-mundo
on: [push]
  setup-run-java:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-java@v3
    with:
      distribution: 'oracle'
      java-version: '17'
  - run: java -cp java HelloWorld.java
  
